<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>

    <Company>Tobias Netzer</Company>
    <Copyright>© 2025-$([System.DateTime]::Now.Year) Tobias Netzer</Copyright>
    <Product>ATLab</Product>
    <Description>Automated Testing Toolkit for the Test Interface Adapter Hardware</Description>
    <FileVersion>1.0.0</FileVersion>
    <InformationalVersion>1.0.0</InformationalVersion>
    <ApplicationIcon>Assets/AppIcon.ico</ApplicationIcon>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    
    <BuildDate>$([System.DateTime]::Now.ToString("dd.MM.yyyy HH:mm:ss"))</BuildDate>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AssemblyMetadata Include="BuildDate" Value="$(BuildDate)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.4" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.0.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.4" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.4" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.4" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="HidSharp" Version="2.6.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
    <PackageReference Include="NationalInstruments.Visa" Version="25.5.0.13" />
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.9.50">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="QuestPDF" Version="2026.6.0" />
    <PackageReference Include="System.IO.Ports" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Fail.png" />
    <EmbeddedResource Include="Assets\Pass.png" />
    <EmbeddedResource Include="Assets\AppIcon.png" />
  </ItemGroup>
</Project>
